name: qgis-test-env
channels:
  - conda-forge
  - defaults
dependencies:
  - qgis
  - pytest
  - pytest-qt
  - pytest-cov
  - pip
  - pip:
      - pytest-qgis
      - python-dateutil
      - pytz
      - wheel
