name: QGIS Plugin Repository Checks

on: [push]

jobs:
  qgis_repo_checks:
    name: Mirror plugins.qgis.org upload scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/qgis-repo-checks
        with:
          root: Mergin
